name: Angular App CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Angular CLI
      run: |
        npm install -g @angular/cli@16.2.12 --skip-confirmation
        ng add @angular/platform-server@16.2.12

    - name: Install project dependencies
      run: npm install

    - name: Build Angular App for SSR
      run: npm run prerender

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/mediumclone_angular/browser
        publish_branch: gh-pages
        force_orphan: true
